### ISSUE TITLE
Which hash function to be used?

### ISSUE THREAD

**Issue by aceshim** [swishlabsco/cosmos-ethereum-bridge#25]
Under "Using the bridge" section vi, 

> _recipient = [HASHED_COSMOS_RECIPIENT_ADDRESS] (for testuser cosmos1pjtgu0vau2m52nrykdpztrt887aykue0hq7dfh, enter "0x636f736d6f7331706a74677530766175326d35326e72796b64707a74727438383761796b756530687137646668") 

which hash function did you use?

I've tried a few, but couldn't specify.

**Comment by denalimarsh** [comment]
The _recipient parameter is hex encoded - not hashed. Issue can be resolved by updating the README from `[HASHED_COSMOS_RECIPIENT_ADDRESS]` to `[HEXADECIMAL_COSMOS_RECIPIENT_ADDRESS]`.

**Comment by denalimarsh** [comment]
Please reference https://github.com/cosmos/peggy for the most up-to-date version of the project.
